#pragma once

// Helper macro
#define ANSI_STRINGIFY(v) #v
#define ANSI_STRINGIFY_LAYERED(v) ANSI_STRINGIFY(v)

// Default macros
#define ANSI_ESCAPE				"\x1b"
#define ANSI_STYLE(c)			ANSI_ESCAPE "[" ANSI_STRINGIFY(c) "m"
#define ANSI_FG_STYLE_256(c)	ANSI_ESCAPE "[38;5;" ANSI_STRINGIFY(c) "m"
#define ANSI_BG_STYLE_256(c)	ANSI_ESCAPE "[48;5;" ANSI_STRINGIFY(c) "m"
#define ANSI_RESET				ANSI_STYLE(0)

// Colors
#define ANSI_FG_BLACK			ANSI_STYLE(30)
#define ANSI_BG_BLACK			ANSI_STYLE(40)
#define ANSI_FG_RED				ANSI_STYLE(31)
#define ANSI_BG_RED				ANSI_STYLE(41)
#define ANSI_FG_GREEN			ANSI_STYLE(32)
#define ANSI_BG_GREEN			ANSI_STYLE(42)
#define ANSI_FG_YELLOW			ANSI_STYLE(33)
#define ANSI_BG_YELLOW			ANSI_STYLE(43)
#define ANSI_FG_BLUE			ANSI_STYLE(34)
#define ANSI_BG_BLUE			ANSI_STYLE(44)
#define ANSI_FG_MAGENTA			ANSI_STYLE(35)
#define ANSI_BG_MAGENTA			ANSI_STYLE(45)
#define ANSI_FG_CYAN			ANSI_STYLE(36)
#define ANSI_BG_CYAN			ANSI_STYLE(46)
#define ANSI_FG_WHITE			ANSI_STYLE(37)
#define ANSI_BG_WHITE			ANSI_STYLE(47)
#define ANSI_FG_RGB(r, g, b)	ANSI_ESCAPE "[38;2;" ANSI_STRINGIFY(r) ";" ANSI_STRINGIFY(g) ";" ANSI_STRINGIFY(b) "m"
#define ANSI_BG_RGB(r, g, b)	ANSI_ESCAPE "[48;2;" ANSI_STRINGIFY(r) ";" ANSI_STRINGIFY(g) ";" ANSI_STRINGIFY(b) "m"
#define ANSI_FG_DEFAULT			ANSI_STYLE(39)
#define ANSI_BG_DEFAULT			ANSI_STYLE(49)

// Styles
#define ANSI_BEGIN_BOLD				ANSI_STYLE(1)
#define ANSI_END_BOLD				ANSI_STYLE(22)
#define ANSI_BEGIN_FAINT			ANSI_STYLE(2)
#define ANSI_END_FAINT				ANSI_STYLE(22)
#define ANSI_BEGIN_ITALIC			ANSI_STYLE(3)
#define ANSI_END_ITALIC				ANSI_STYLE(23)
#define ANSI_BEGIN_UNDERLINE		ANSI_STYLE(4)
#define ANSI_END_UNDERLINE			ANSI_STYLE(24)
#define ANSI_BEGIN_BLINKING			ANSI_STYLE(5)
#define ANSI_END_BLINKING			ANSI_STYLE(25)
#define ANSI_BEGIN_INVERT			ANSI_STYLE(7)
#define ANSI_END_INVERT				ANSI_STYLE(27)
#define ANSI_BEGIN_HIDDEN			ANSI_STYLE(8)
#define ANSI_END_HIDDEN				ANSI_STYLE(28)
#define ANSI_BEGIN_STRIKETHROUGH	ANSI_STYLE(9)
#define ANSI_END_STRIKETHROUGH		ANSI_STYLE(29)

// Style wrappers
#define ANSI_BOLD(str)			ANSI_BEGIN_BOLD				str	ANSI_END_BOLD
#define ANSI_FAINT(str)			ANSI_BEGIN_FAINT			str	ANSI_END_FAINT
#define ANSI_ITALIC(str)		ANSI_BEGIN_ITALIC			str	ANSI_END_ITALIC
#define ANSI_UNDERLINE(str)		ANSI_BEGIN_UNDERLINE		str	ANSI_END_UNDERLINE
#define ANSI_BLINKING(str)		ANSI_BEGIN_BLINKING			str	ANSI_END_BLINKING
#define ANSI_INVERT(str)		ANSI_BEGIN_INVERT			str	ANSI_END_INVERT
#define ANSI_HIDDEN(str)		ANSI_BEGIN_HIDDEN			str	ANSI_END_HIDDEN
#define ANSI_STRIKETHROUGH(str)	ANSI_BEGIN_STRIKETHROUGH	str	ANSI_END_STRIKETHROUGH