#pragma once
#include "engine/engine_common.hpp"

namespace IW8 {
	enum class AdsOffsetInterpolationType : int {
		ADS_OFFSET_INTERP_TYPE_LINEAR = 0x0,
		ADS_OFFSET_INTERP_TYPE_EASEINOUTSINE = 0x1,
		ADS_OFFSET_INTERP_TYPE_EASEINOUTSMOOTHERSTEP = 0x2,
		ADS_OFFSET_INTERP_TYPE_EASEINCUBIC = 0x3,
		ADS_OFFSET_INTERP_TYPE_EASEOUTCUBIC = 0x4,
		ADS_OFFSET_INTERP_TYPE_EASEINQUARTIC = 0x5,
		ADS_OFFSET_INTERP_TYPE_EASEOUTQUARTIC = 0x6,
		ADS_OFFSET_INTERP_TYPE_EASEINEXPO = 0x7,
		ADS_OFFSET_INTERP_TYPE_EASEOUTEXPO = 0x8,
		ADS_OFFSET_INTERP_TYPE_COUNT = 0x9
	};
}
