#pragma once
#include "engine/engine_common.hpp"

namespace IW8 {
	enum class bdPlatformType : std::int8_t {
		PLATFORM_TYPE_UNKNOWN = 0x0,
		PLATFORM_TYPE_ANDROID = 0x1,
		PLATFORM_TYPE_BATTLENET = 0x2,
		PLATFORM_TYPE_IOS = 0x3,
		PLATFORM_TYPE_KINDLE_FIRE = 0x4,
		PLATFORM_TYPE_PS3 = 0x5,
		PLATFORM_TYPE_PS4 = 0x6,
		PLATFORM_TYPE_PS5 = 0x7,
		PLATFORM_TYPE_STEAM = 0x8,
		PLATFORM_TYPE_STUDIO = 0x9,
		PLATFORM_TYPE_SWITCH = 0xA,
		PLATFORM_TYPE_UNO = 0xB,
		PLATFORM_TYPE_UWP = 0xC,
		PLATFORM_TYPE_WE_GAME = 0xD,
		PLATFORM_TYPE_WII = 0xE,
		PLATFORM_TYPE_WIIU = 0xF,
		PLATFORM_TYPE_XBOX_360 = 0x10,
		PLATFORM_TYPE_XBOX_ONE = 0x11,
		PLATFORM_TYPE_XBOX_TWO = 0x12,
		PLATFORM_TYPE_ATVI_DEDICATED = 0x13,
		PLATFORM_TYPE_DEDICATED = 0x14,
		PLATFORM_TYPE_HOST_LICENSE = 0x15,
		PLATFORM_TYPE_SINGLE_IDENTITY = 0x16,
		PLATFORM_TYPE_USER_LICENSE = 0x17,
		PLATFORM_TYPE_EPIC = 0x18
	};
}
