#pragma once
#include "engine/engine_common.hpp"

namespace IW8 {
	enum class DynamicAttachmentType : int {
		DYNAMIC_ATTACHMENT_TYPE_MUZZLE = 0x0,
		DYNAMIC_ATTACHMENT_TYPE_UNDERBARREL = 0x1,
		DYNAMIC_ATTACHMENT_TYPE_LASER = 0x2,
		DYNAMIC_ATTACHMENT_TYPE_GUARD = 0x3,
		DYNAMIC_ATTACHMENT_TYPE_MAGAZINE = 0x4,
		DYNAMIC_ATTACHMENT_TYPE_RECEIVER = 0x5,
		DYNAMIC_ATTACHMENT_TYPE_SCOPE = 0x6,
		DYNAMIC_ATTACHMENT_TYPE_STOCK = 0x7,
		DYNAMIC_ATTACHMENT_TYPE_FIRETYPE = 0x8,
		DYNAMIC_ATTACHMENT_TYPE_BARREL = 0x9,
		DYNAMIC_ATTACHMENT_TYPE_OTHER = 0xA,
		DYNAMIC_ATTACHMENT_TYPE_COUNT = 0xB
	};
}
